version: "3.4"

# networks:
#   docker-network:
#     driver: bridge

services:
  redis:
    image: redis:latest
    container_name: ledger-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    # networks:
    # - docker-network
  db:
    container_name: ledger-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # networks:
    #   - docker-network

  # job-consumer:
  #   build:
  #     context: .
  #     dockerfile: job-consumer.Dockerfile
  #   container_name: job-consumer-app
  #   env_file:
  #     - .env
  #   ports:
  #     - "3001:3001"
      # networks:
      # - docker-network
    # depends_on:
    #   - redis
    #   - db
  # ledger:
  #   build:
  #     context: .
  #     dockerfile: ledger.Dockerfile
  #   container_name: ledger-app
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   # networks:
  #   #   - docker-network
  #   depends_on:
  #     - redis
  #     - db
    # environment:
    #   - REDIS_HOST=ledger-redis
      # - job-consumer